### ISSUE TITLE
NoSuchMethodError: No static method getLogger(Ljava/lang/String;)Ljava/lang/System$Logger

### ISSUE THREAD

**Issue by ghost** [SandroHc/reactive-jikan#10]
Hello, im kinda new to APIS and Wrappers, I tried to use this, but Im getting an error.

`
java.lang.NoSuchMethodError: No static method getLogger(Ljava/lang/String;)Ljava/lang/System$Logger; in class Ljava/lang/System; or its super classes (declaration of 'java.lang.System' appears in /apex/com.android.art/javalib/core-oj.jar)`

**Comment by SandroHc** [comment]
Hello @Shootstylee. I see that you're trying to use this library on an Android application, can you give me more details to reproduce your issue, like a snippet of your code and the Android API version?

**Comment by ghost** [comment]
Hello @SandroHc, Thanks for the fast answer.
The minumun SDK version is on 28// Android P, Im using the examples you gave in the Readme.


 ```
   Jikan jikan = new Jikan();

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        getData();

    }

    private void getData() {

        try {
            Anime anime = jikan.query().anime().get(1)
                    .execute()
                    .block();
            Collection<Anime> results = jikan.query().anime().search()
                    .query("sword art online")
                    .limit(5)
                    .status(AnimeStatus.AIRING)
                    .orderBy(AnimeOrderBy.MEMBERS, SortOrder.ASCENDING)
                    .execute()
                    .collectList()
                    .block();
        }catch (Exception e) {
            e.printStackTrace();
        }

    }

}
```

**Comment by SandroHc** [comment]
The issue is caused by the Caffeine library, which does not support Android (https://github.com/ben-manes/caffeine/issues/293). I will remove it from reactive-jikan and leave the caching details for the developers to implement.

**Comment by SandroHc** [comment]
Released v2.1.0 that fixes this issue. @Shootstylee, can you please upgrade to this new version?

The following may be necessary for reactive-jikan/Netty to work on Android (https://github.com/reactor/reactor-netty/issues/1447):
```java
Jikan jikan = new Jikan.JikanBuilder()
        .httpClientCustomizer(httpClient -> httpClient.resolver(DefaultAddressResolverGroup.INSTANCE))
        .build();
```

**Comment by Shootstylee** [comment]
Ah, Thanks I used the new code, but I now have problems with netty

`No implementation found for int io.netty.internal.tcnative.Library.aprMajorVersion() (tried Java_io_netty_internal_tcnative_Library_aprMajorVersion and Java_io_netty_internal_tcnative_Library_aprMajorVersion__)`

Maybe I am doing something wrong?

**Comment by ghost** [comment]
Hey, thanks again for the quick response and fix!
I tried out the new code, and it got rid of the chach problem, but now I am facing another issue. This time with Netty

```
No implementation found for int io.netty.internal.tcnative.Library.aprMajorVersion() (tried Java_io_netty_internal_tcnative_Library_aprMajorVersion and Java_io_netty_internal_tcnative_Library_aprMajorVersion__)
No implementation found for int io.netty.channel.epoll.Native.offsetofEpollData() (tried Java_io_netty_channel_epoll_Native_offsetofEpollData
```

There is also sadly no way to implement netty into android studio since they dont provide any because of the JDK.

**Comment by SandroHc** [comment]
Was not able to reproduce your issue; tried with `minSdk 28` and Java 8.

Found that Netty only supports Java 8+ (https://github.com/netty/netty-tcnative/issues/443) and that it does not officially support Android (https://github.com/netty/netty/issues/10029).

If all else fails, you may want to try and downgrade the "reactor-netty" version by copying the following to your dependencies block on build.gradle (https://github.com/SandroHc/reactive-jikan/issues/3):
`implementation 'io.projectreactor.netty:reactor-netty:0.9.10.RELEASE'`

**Comment by ghost** [comment]
Hello, I sadly could not fix this issue, however I decided to pull the data with volley, thanks for the help 👍🏻
