### ISSUE TITLE
Anime themes has type Collection<GenreEntity<AnimeGenre>>

### ISSUE THREAD

**Issue by fbaierl** [SandroHc/reactive-jikan#12]
I am not sure if maybe I am  misunderstanding something here, but the themes inside the Anime class are defined like this:

```
	/** The themes. */
	public Collection<GenreEntity<AnimeGenre>> themes = Collections.emptyList();
```

Isn't this the wrong type?

**Comment by SandroHc** [comment]
It looks like so at first glance, but MyAnimeList sees genres and themes as the same thing internally. Let's use Sword Art Online as an example ([Jikan](https://api.jikan.moe/v4/anime/11757), [MAL](https://myanimelist.net/anime/11757/Sword_Art_Online)). If we check the `url`s for themes, they all point to genres:

```json
{
	"data": {
		...
		"genres": [
			{
				"mal_id": 1,
				"type": "anime",
				"name": "Action",
				"url": "https:\/\/myanimelist.net\/anime\/genre\/1\/Action"
			},
			...
		],
		...
		"themes": [
			{
				"mal_id": 64,
				"type": "anime",
				"name": "Love Polygon",
				"url": "https:\/\/myanimelist.net\/anime\/genre\/64\/Love_Polygon"
			},
			...
		]
	}
}
```

What I also noticed is that `AnimeGenre` and possibly `MangaGenre` are now outdated, as MAL seems to have added 38 new genres/themes that we don't have available.

Thank you for this issue into my attention. I'll prepare a new release to include the new genres.

**Comment by fbaierl** [comment]
Ah I see, this seems to be my misunderstanding then. I thought "themes" referes to the opening and ending soundtracks. 

Thanks for your fast reply.

**Comment by SandroHc** [comment]
Yup, kind of confusing for MAL/Jikan to call openings and endings themes. Unfortunately that information has to be fetched separately, via `AnimeThemesQuery` or `jikan.query().anime().themes(animeId).execute().block()`.
