### ISSUE TITLE
Manga search excluding hentai results in only hentai manga being returned 

### ISSUE THREAD

**Issue by fbaierl** [SandroHc/reactive-jikan#7]
When calling:

```
 _jikan.query().manga().search().page(page).query(query)
        .genres(MangaGenre.HENTAI)
        .excludeGivenGenres()
        .execute()
        .retryWhen(Retry.backoff(BACKOFF_ATTEMPTS, java.time.Duration.ofMillis(BACKOFF_MILLIS)))
        .collect(Collectors.toList())
        .doOnError(e -> Log.e(TAG, "Error searching for Manga with query: " + query + "." + e.toString()))
        .onErrorResume(a -> Mono.just(new ArrayList<>()))
        .block();
```

I get a list of only hentai mangas. Pretty sure the `excludeGivenGenres()` part is broken.

**Comment by SandroHc** [comment]
Great catch! The `exclude_genre` flag was inverted and the [official documentation](https://jikan.docs.apiary.io/#reference/0/search) has vague wording for the flag.

I'll release version 1.0.2 shortly to fix the issue.

**Comment by SandroHc** [comment]
Version 1.0.2 has been released to [Maven Central](https://repo.maven.apache.org/maven2/net/sandrohc/reactive-jikan/).

This issue can be closed once you confirm the fix is working. :)

**Comment by fbaierl** [comment]
Great! That was very fast, thanks a lot.

**Comment by fbaierl** [comment]
Can confirm that the new version works, so I will close this issue. Thanks again.
